edition = "2024"
style_edition = "2024"
use_small_heuristics = "Max"
fn_args_layout = "Tall"
max_width = 100
reorder_modules = true
wrap_comments = true
normalize_comments = true
use_try_shorthand = true
match_block_trailing_comma = true
use_field_init_shorthand = true
condense_wildcard_suffixes = true
imports_granularity = "Crate"
array_width = 80
attr_fn_like_width = 80
chain_width = 80
comment_width = 100
fn_call_width = 80
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
newline_style = "Unix"
reorder_imports = true
single_line_if_else_max_width = 60
single_line_let_else_max_width = 60
struct_lit_width = 40
struct_variant_width = 40
